### PR TITLE
Add switch to show current architecture

### PR DESCRIPTION
**Pull request by dberzano**

### CODE REVIEW

**Comment by dberzano** [comment]
@ktf what do you think of having something like this to pass to alienv for autodetecting the arch?

**Comment by ktf** [comment]
Why not simply printing it out always? E.g.:

```
aliBuild 1.4.5 (osx_x86-64)
```

**Comment by dberzano** [comment]
That too, you are right. I would however retain the `--show-architecture` switch for making it easier to use in `alienv` without any parsing, what do you think? (I am working on it.)

**Comment by ktf** [comment]
Fine with me. But then again, why simply not implementing the "architecture" sub-command?

**Comment by dberzano** [comment]
That too yes if you prefer :-D

**Comment by dberzano** [comment]
@ktf better?

**Pull request merged**
